# .github/workflows/deploy.yml
name: Deploy DAGs to Astronomer

on:
  push:
    branches:
      - main
    paths:
      - 'dags/**'     # Trigger only if files in dags/ are changed

env:
  ## Set API Token as an environment variable
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy to Astro
        uses: astronomer/deploy-action@v0.10.1
        with:
          deployment-id: cmbzds0op1vtm01j0e79sk0yc
          parse: true
