name: Run Python Scripts

on:
  push:
    paths:
      - 'python_scripts/**/main.py'  # Trigger only if any main.py changes

jobs:
  run-main-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Find and run changed main.py files
      run: |
        echo "Looking for changed main.py files..."
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^python_scripts/.*/main.py$' || true)

        if [ -z "$changed_files" ]; then
          echo "No main.py files changed."
          exit 0
        fi

        for file in $changed_files; do
          echo "Running $file..."
          python "$file"
        done
