name: Deploy to Astronomer

on:
  push:
    branches:
      - main
    paths:
      - 'astro_project/dags/**'

env:
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Print debug info
        run: |
          echo "DEPLOYMENT_ID is set? ${{ secrets.DEPLOYMENT_ID != '' }}"
          echo "ASTRO_API_TOKEN is set? ${{ secrets.ASTRO_API_TOKEN != '' }}"
          echo "Listing contents of astro_project/.astro:"
          ls -l astro_project/.astro || echo " .astro folder missing!"
          echo "Listing files in astro_project:"
          ls -l astro_project

      - name: Deploy to Astronomer
        uses: astronomer/deploy-action@v0.10.1
        with:
          deployment-id: ${{ secrets.DEPLOYMENT_ID }}
          root-folder: astro_project
