name: Run main.py on Push to Main

on:
  push:
    branches:
      - main
    paths:
      - 'python_scripts/**/main.py'

jobs:
  run-main-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Fetch enough history for commit diff

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Find and run changed main.py files
      run: |
        echo "Looking for changed main.py files in the last commit..."

        mkdir -p outputs

        # Get list of changed/added main.py files in the last commit
        changed_files=$(git diff --name-only HEAD~1 HEAD | grep '^python_scripts/.*/main.py$' || true)

        if [ -z "$changed_files" ]; then
          echo "No main.py files changed in this commit."
          exit 0
        fi

        for file in $changed_files; do
          echo "Running $file..."
          folder_name=$(dirname "$file" | sed 's|/|_|g')
          log_file="outputs/${folder_name}_output.log"
          python "$file" > "$log_file" 2>&1
          echo "Output saved to $log_file"
        done

    - name: Upload script output logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: main-py-logs
        path: outputs/*.log
