name: Run main.py on PR Push

on:
  pull_request:
    paths:
      - 'python_scripts/**/main.py'

jobs:
  run-main-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Get full git history

    - name: Fetch base branch manually
      run: |
        echo "Fetching base branch: ${{ github.base_ref }}"
        git fetch origin ${{ github.base_ref }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Find and run changed main.py files
      run: |
        echo "Looking for main.py files changed in this PR..."

        mkdir -p outputs

        # Get changed main.py files between base and PR head
        changed_files=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep '^python_scripts/.*/main.py$' || true)

        if [ -z "$changed_files" ]; then
          echo "No main.py files changed in this PR."
          exit 0
        fi

        for file in $changed_files; do
          echo "Running $file..."
          folder_name=$(dirname "$file" | sed 's|/|_|g')
          log_file="outputs/${folder_name}_output.log"
          python "$file" > "$log_file" 2>&1
          echo "Output saved to $log_file"
        done

    - name: Upload script output logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: main-py-logs
        path: outputs/*.log
