name: Deploy to Astronomer

on:
  push:
    branches:
      - main
    paths:
      - 'astro_project/dags/**'  # Only trigger when DAG files change

env:
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Astro
        uses: astronomer/deploy-action@v0.10.1
        with:
          deployment-id: cmbzfs7wb1wjz01j07bij6tsn
          parse: true
          working-directory: astro_project  
