name: Deploy to Astronomer

on:
  push:
    branches:
      - main
    paths:
      - 'astro_project/dags/**'  # Trigger only when DAGs change

env:
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Astronomer
        uses: astronomer/deploy-action@v0.10.1
        with:
          deployment-id: ${{ secrets.DEPLOYMENT_ID }}
          working-directory: astro_project
