name: Deploy Astro DAGs

on:
  push:
    branches:
      - main
    paths:
      - 'astro_project/dags/**'  # Update `astro_project` if your project folder is named differently

jobs:
  deploy:
    name: Deploy DAGs to Astronomer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Astro CLI
        run: curl -sSL https://install.astronomer.io | sudo bash

      - name: Authenticate with Astronomer
        run: astro auth login --token ${{ secrets.ASTRO_API_TOKEN }}

      - name: Deploy to Astronomer
        run: |
          cd astro_project
          astro deploy --force
